# This file was *autogenerated* from the file fibonacci.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_12 = Integer(12)#### fibonacci.sage : Prints the first eleven Fibonacci numbers
#### Author: <Your Name Here>
#### Date: <Today's Date>

## Fibonacci : Computes the nth Fibonacci number
 # @param n: Natural number n >= 0
 # @return:  The nth Fibonacci number
## 
def Fibonacci(n):
     if n <= _sage_const_0 :
          return _sage_const_0 
     elif n == _sage_const_1 :
          return _sage_const_1 
     fibNumbers = [_sage_const_0 , _sage_const_1 ]
     for n in range(_sage_const_2 , n + _sage_const_1 ):
          fibNum = fibNumbers[n - _sage_const_1 ] + fibNumbers[n - _sage_const_2 ]
          fibNumbers += [fibNum]
     ##
     return fibNumbers[n]
##
 
## Print the first 11 Fibonacci numbers in the specified format: 
print "The First Fibonacci Numbers:"
for n in range(_sage_const_0 , _sage_const_12 ):
     print "   >> Fib(%2d) = %d" % (n, Fibonacci(n))
##

